[package]
name = "tauri-plugin-auditaur"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Development-first Tauri plugin for collecting Auditaur local telemetry."
readme = "README.md"
categories = ["development-tools::debugging"]
keywords = ["tauri", "plugin", "observability", "opentelemetry"]
links = "tauri-plugin-auditaur"

[dependencies]
auditaur-collector = { version = "0.2.2", path = "../auditaur-collector" }
auditaur-core = { version = "0.2.2", path = "../auditaur-core" }
directories.workspace = true
serde.workspace = true
serde_json.workspace = true
tauri-plugin-auditaur-macros = { version = "0.2.2", path = "../tauri-plugin-auditaur-macros" }
tauri.workspace = true
time.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true

[build-dependencies]
tauri-plugin = { version = "2.6.2", features = ["build"] }
